### ISSUE TITLE
Android app will show 'fetching JS bundle' randomly when open for a while

### ISSUE THREAD

**Issue by jsierles** [rnplay/rnplay-native#24]
After entering and exiting a few apps, then leaving the main app open for ~10 minutes, it displays 'Fetching JS bundle' 3-4 times. Eventually this goes away, but it causes the Android simulator to freeze.

**Comment by dsibiski** [comment]
The reason this was happening stems from the fact that we use a single packager for all apps. If an app is open on a device and "Live Reload" is turned on, any changes made, to any app (across all of rnplay) will cause a reload of that open app. (Not desirable!)

The issue was compounded in Android because the "app" activities stick around in memory longer than they do in iOS. Also, they popup this global dialog/spinner when they reload. If you had opened 5 or 6 apps, it's possible that they are all still in memory (until the OS kills them) and so if someone saved an app on the website, all 5 or 6 of those apps would refresh. Open enough of them and it would crash the app/device.

The ultimate solution is moving away from the "one packager to rule them all", but that is a large task. To mitigate this problem for the time being, we simply don't have "Live Reload" turned on by default. Not a 100% solution but it works for now.
